settings:
  parallel: true

driver:
  name: docker
  # privileged is required otherwise the container doesn't boot right
  privileged: true

platforms:
- name: centos-5
  driver:
    image: centos:5

- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7

suites:
- name: connectors
  run_list:
  - recipe[yum-mysql-community::connectors]
  attributes: {}

- name: mysql56
  run_list:
  - recipe[yum-mysql-community::mysql56]
  attributes: {}

- name: mysql57
  run_list:
  - recipe[yum-mysql-community::mysql57]
  attributes: {}
